name: Deploy Hugo Blog to GitHub Pages

on:
  push:
    branches:
      - main  # main 브랜치에 푸시될 때 실행

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          submodules: true  # ✅ 테마가 Git 서브모듈이면 true 설정

      - name: Setup Hugo
        uses: peaceiris/actions-hugo@v2
        with:
          hugo-version: 'latest'  # 최신 Hugo 버전 사용

      - name: Build site
        run: hugo --minify  # 사이트 빌드 (압축하여 최적화)

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./public  # Hugo가 생성한 `public` 폴더를 GitHub Pages에 배포
